# Override the static config at /var/lib/rancher/k3s/server/manifests/traefik-config.yaml

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    dashboard:
      enabled: true
    api:
      dashboard: true
      insecure: true
    ports:
      web:
        port: 8000
        expose: true
        exposedPort: 8080
      tcp:
        port: 9090
        expose: true
        exposedPort: 9090
      docker:
        port: 9999
        expose: true
        exposedPort: 9999
    logs:
      access:
        enabled: true